
import { PowerliftingRecord, Region, AgeCategory, LiftType, Notification } from './types';

export const REGIONS: Region[] = Object.values(Region);
export const AGE_CATEGORIES: AgeCategory[] = Object.values(AgeCategory);
export const LIFT_TYPES: LiftType[] = Object.values(LiftType);
export const GENDERS: ('Male' | 'Female')[] = ['Male', 'Female'];
export const MALE_BW_CATEGORIES: string[] = ['U53kg', 'U59kg', 'U66kg', 'U74kg', 'U83kg', 'U93kg', 'U105kg', 'U120kg', '120kg+'];
export const FEMALE_BW_CATEGORIES: string[] = ['U47kg', 'U52kg', 'U57kg', 'U63kg', 'U69kg', 'U76kg', 'U84kg', '84kg+'];

export const REGIONAL_SOURCE_URLS: Record<Region, { Male: string; Female: string; }> = {
    [Region.British]: { Male: 'https://www.britishpowerlifting.org/documents/4066_male_classic_records_02-10-25.pdf', Female: 'https://www.britishpowerlifting.org/documents/4067_female_classic_records_02-10-25.pdf' },
    [Region.England]: { Male: 'https://drive.google.com/file/d/1YYyQD_wo9BmPp6PDPOcy9MXG5sZeLbxY/view', Female: 'https://drive.google.com/file/d/15h29Ij3JQs8wvSTyVZH_Or42MCoauuuL/view' },
    [Region.Wales]: { Male: 'https://docs.google.com/spreadsheets/d/1HpEj2OmELnvpIXNaQokrjJDBwV7HchlkSs_nUFU6qQQ/edit?gid=750758101#gid=750758101', Female: 'https://docs.google.com/spreadsheets/d/1HpEj2OmELnvpIXNaQokrjJDBwV7HchlkSs_nUFU6qQQ/edit?gid=1671380863#gid=1671380863' },
    [Region.Scotland]: { Male: 'https://docs.google.com/spreadsheets/d/1DpR9Q9cwm8zUul2EkIBfSnA1kUUPQ5Zsj0-1BHwN-Ao/edit?gid=2075817735#gid=2075817735', Female: 'https://docs.google.com/spreadsheets/d/1DpR9Q9cwm8zUul2EkIBfSnA1kUUPQ5Zsj0-1BHwN-Ao/edit?gid=1682879510#gid=1682879510' },
    [Region.NorthernIreland]: { Male: '#', Female: '#' },
    [Region.NorthWest]: { Male: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRZzscIj0x3A9TwbYj5T4Nw52ul9IJy3HVwF7PtNcp-Jqbju08a2mhRVYYVbMh_saoRb9nFGLwGWf7r/pubhtml', Female: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTvLJX-PfQhGnudhX1jl5WJQiJQBG6EgepZCntji2egYixmQsJ_nOjGNE619a0XXzTCZfFaq0nMEK_y/pubhtml' },
    [Region.YorkshireNorthEast]: { Male: 'https://docs.google.com/spreadsheets/d/1QmF02GZlEmZ6sqZRgF53EjAgNq3KDF8Z-69hYNcNLI0/pub?gid=228906170&single=true&output=pdf', Female: 'https://docs.google.com/spreadsheets/d/1tSfPPCuSbfr7iWW4_qjHZaSdF6zfhsoINDLFwza8Hx4/pub?gid=360505567&single=true&output=pdf' },
    [Region.NorthMidlands]: { Male: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR1obCGzxyrLrvsOpWlEN5qVgy_hgnbmkhP-1VdY82N9VCzqM6s0ZA6s7ZTl3YvU7pSzvrB5LjQpFbX/pubhtml?gid=0&single=true', Female: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSufUiD2qXxkZ7v4FVeLSTrNpiZkEi36NTrdG8FGTFj4_o536feNXP1ROHhPcWhSoDFAcHDzAbEWIp3/pubhtml?gid=0&single=true' },
    [Region.WestMidlands]: { Male: 'https://www.westmidspowerlifting.co.uk/wp-content/uploads/2025/10/male-classic-records-21.9.25.pdf', Female: 'https://www.westmidspowerlifting.co.uk/wp-content/uploads/2025/10/female-classic-records-21.9.25.pdf' },
    [Region.GreaterLondon]: { Male: '#', Female: '#' },
    [Region.EastMidlands]: { Male: 'https://drive.google.com/file/d/1bzTKOoWLnu3_Io7BkTOA23pmSmhCKpq7/view', Female: 'https://drive.google.com/file/d/1Nr1VvsziYVpwAmstBo4KvYFEpFQklbcU/view' },
    [Region.SouthMidlands]: { Male: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR337Y08wlVNV3hHILrgmmG5UsCnh6ct8Y75n1VFlWET_ORZSlYf__Nyh4nSf607KbT85ffYAylkKni/pubhtml?gid=378547137&single=true', Female: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR337Y08wlVNV3hHILrgmmG5UsCnh6ct8Y75n1VFlWET_ORZSlYf__Nyh4nSf607KbT85ffYAylkKni/pubhtml?gid=92206694&single=true' },
    [Region.SouthWest]: { Male: 'https://www.swpla.co.uk/_files/ugd/e4f953_4be5da18fc424b979f31a70716754944.pdf?index=true', Female: 'https://www.swpla.co.uk/_files/ugd/e4f953_e917f6be40834665ad66ef27fb910506.pdf?index=true' },
    [Region.SouthEast]: { Male: 'https://drive.google.com/file/d/1kRh1PfkW1KgKg0Yk62tR5aNj-BRX5_IT/view', Female: 'https://drive.google.com/file/d/1r5k7ziKFcSZVVJ50UhGoKJI4zczYAYjR/view' },
};

export const REGIONAL_LANDING_PAGE_URLS: Record<Region, { Male: string; Female: string; }> = {
    [Region.British]: { Male: 'https://www.britishpowerlifting.org/classic-records', Female: 'https://www.britishpowerlifting.org/classic-records' },
    [Region.England]: { Male: '', Female: '' },
    [Region.Wales]: { Male: '', Female: '' },
    [Region.Scotland]: { Male: '', Female: '' },
    [Region.NorthernIreland]: { Male: '', Female: '' },
    [Region.NorthWest]: { Male: '', Female: '' },
    [Region.YorkshireNorthEast]: { Male: '', Female: '' },
    [Region.NorthMidlands]: { Male: '', Female: '' },
    [Region.WestMidlands]: { Male: 'https://www.westmidspowerlifting.co.uk/records/', Female: 'https://www.westmidspowerlifting.co.uk/records/' },
    [Region.GreaterLondon]: { Male: '', Female: '' },
    [Region.EastMidlands]: { Male: '', Female: '' },
    [Region.SouthMidlands]: { Male: '', Female: '' },
    [Region.SouthWest]: { Male: 'https://www.swpla.co.uk/records', Female: 'https://www.swpla.co.uk/records' },
    [Region.SouthEast]: { Male: '', Female: '' },
};


export const MOCK_NOTIFICATIONS: Notification[] = [
    {
        id: 1,
        region: Region.NorthWest,
        date: '2024-07-28',
        sourceType: 'Google Sheet',
        gender: 'Male',
        sourceUrl: REGIONAL_SOURCE_URLS[Region.NorthWest].Male,
    },
    {
        id: 2,
        region: Region.Scotland,
        date: '2024-07-27',
        sourceType: 'Google Sheet',
        gender: 'Female',
        sourceUrl: REGIONAL_SOURCE_URLS[Region.Scotland].Female,
    },
    {
        id: 3,
        region: Region.Wales,
        date: '2024-07-25',
        sourceType: 'Google Sheet',
        gender: 'Female',
        sourceUrl: REGIONAL_SOURCE_URLS[Region.Wales].Female,
    }
]

export const MOCK_RECORDS: PowerliftingRecord[] = [
  {
    id: 1,
    lifterName: 'John Smith',
    region: Region.NorthWest,
    ageCategory: AgeCategory.Open,
    bodyweightCategory: 'U93kg',
    gender: 'Male',
    liftType: LiftType.Squat,
    weightKg: 300,
    dateSet: '2023-10-15',
    competition: 'NW Championships',
  },
  {
    id: 2,
    lifterName: 'Emily Jones',
    region: Region.Scotland,
    ageCategory: AgeCategory.Junior,
    bodyweightCategory: 'U63kg',
    gender: 'Female',
    liftType: LiftType.Deadlift,
    weightKg: 185.5,
    dateSet: '2023-09-20',
    competition: 'Scottish Open',
  },
  {
    id: 3,
    lifterName: 'David Williams',
    region: Region.Wales,
    ageCategory: AgeCategory.Masters1,
    bodyweightCategory: 'U83kg',
    gender: 'Male',
    liftType: LiftType.Bench,
    weightKg: 190,
    dateSet: '2024-01-12',
    competition: 'Welsh Seniors',
  },
    {
    id: 4,
    lifterName: 'Sarah Taylor',
    region: Region.SouthEast,
    ageCategory: AgeCategory.Open,
    bodyweightCategory: 'U57kg',
    gender: 'Female',
    liftType: LiftType.Total,
    weightKg: 450,
    dateSet: '2023-11-05',
    competition: 'SE Divisional',
  },
  {
    id: 5,
    lifterName: 'Michael Brown',
    region: Region.WestMidlands,
    ageCategory: AgeCategory.Open,
    bodyweightCategory: 'U105kg',
    gender: 'Male',
    liftType: LiftType.Deadlift,
    weightKg: 340,
    dateSet: '2023-08-01',
    competition: 'Midlands Powerlifting Meet',
  },
  {
    id: 6,
    lifterName: 'Jessica Evans',
    region: Region.YorkshireNorthEast,
    ageCategory: AgeCategory.SubJunior,
    bodyweightCategory: 'U69kg',
    gender: 'Female',
    liftType: LiftType.Squat,
    weightKg: 130,
    dateSet: '2024-02-18',
    competition: 'Yorkshire Youth Cup',
  },
  {
    id: 7,
    lifterName: 'Gareth Bale',
    region: Region.Wales,
    ageCategory: AgeCategory.Open,
    bodyweightCategory: 'U83kg',
    gender: 'Male',
    liftType: LiftType.Total,
    weightKg: 750,
    dateSet: '2024-01-12',
    competition: 'Welsh Seniors',
  },
  {
    id: 8,
    lifterName: 'Jackson Fountain',
    region: Region.Wales,
    ageCategory: AgeCategory.SubJunior,
    bodyweightCategory: 'U53kg',
    gender: 'Male',
    liftType: LiftType.Squat,
    weightKg: 140,
    dateSet: '2023-10-07',
    competition: 'Welsh U18 Championship',
  },
  {
    id: 9,
    lifterName: 'Jackson Fountain',
    region: Region.Wales,
    ageCategory: AgeCategory.SubJunior,
    bodyweightCategory: 'U53kg',
    gender: 'Male',
    liftType: LiftType.Bench,
    weightKg: 70,
    dateSet: '2023-10-07',
    competition: 'Welsh U18 Championship',
  },
  {
    id: 10,
    lifterName: 'Jackson Fountain',
    region: Region.Wales,
    ageCategory: AgeCategory.SubJunior,
    bodyweightCategory: 'U53kg',
    gender: 'Male',
    liftType: LiftType.Deadlift,
    weightKg: 180,
    dateSet: '2023-10-07',
    competition: 'Welsh U18 Championship',
  },
  {
    id: 11,
    lifterName: 'Jackson Fountain',
    region: Region.Wales,
    ageCategory: AgeCategory.SubJunior,
    bodyweightCategory: 'U53kg',
    gender: 'Male',
    liftType: LiftType.Total,
    weightKg: 390,
    dateSet: '2023-10-07',
    competition: 'Welsh U18 Championship',
  },
  {
    id: 12,
    lifterName: 'Jackson Fountain',
    region: Region.Wales,
    ageCategory: AgeCategory.SubJunior,
    bodyweightCategory: 'U53kg',
    gender: 'Male',
    liftType: LiftType.Bench,
    weightKg: 70,
    dateSet: '2023-10-07',
    competition: 'Welsh U18 Bench Only',
  },
];
